### ISSUE TITLE
3판은 언제쯤 나오게 될까요?

### ISSUE THREAD

**Issue by vEduardovich** [rickiepark/handson-ml3#1]
repository를 보니 그 때가 다가오는 것 같아 문의드립니다.

추가로 Generative Deep Learning 2판 출판일도 함께 문의드립니다.

감사합니다

**Comment by rickiepark** [comment]
@vEduardovich 안녕하세요. 3판 번역을 이제 막 마쳤습니다. 구체적인 출간 일정은 출판사에 문의 부탁드립니다. Generative Deep Learning 2판은 이제 번역을 시작해야 하기 때문에 출간일을 논하기는 아직 이른 것 같습니다. 감사합니다!

**Comment by vEduardovich** [comment]
@rickiepark 이 늦은 시간까지.. 기대하며 기다리고 있겠습니다. 감사합니다!
